### ISSUE TITLE
Support django==3.0

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/django-split-settings#120]

**Comment by lk-geimfari** [comment]
Are there any changes in Django 3.0 that require changes in `django-split-settings`? I've planning to upgrade to Django 3.0 and we use `django-split-settings` in all our projects.

**Comment by sobolevn** [comment]
Nope, I am sure that we don't have to change anything.

Just CI related things to be sure that it works. Will you @lk-geimfari ?

**Comment by lk-geimfari** [comment]
Of course! Tell me please, what exactly should I do?

**Comment by sobolevn** [comment]
Add `django3.0` here: https://github.com/sobolevn/django-split-settings/blob/master/.travis.yml
And here: https://github.com/sobolevn/django-split-settings/blob/master/pyproject.toml#L37
