### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by lk-geimfari** [sobolevn/django-split-settings#134]
Does it support `Python 3.8`? If it does, why not add `3.8` to Travis's config? Or, maybe because of `wemake-style-guide`?

I can work on it if you think that we need this. Thanks.

**Comment by sobolevn** [comment]
Yeap, `wps` does not support `3.8` yet.

**Comment by sobolevn** [comment]
@lk-geimfari btw, what are your plans for this holiday season? Do you want to participate in `WPS 0.14` release?

**Comment by lk-geimfari** [comment]
@sobolevn Previously I have tried to figure out how `WPS` works, but I'm not strong enough in `ast` things (I've never worked with it directly), but if there are easy issues to start I totally can work on it in holidays.

**Comment by sobolevn** [comment]
You can choose from `level:started` 👍

**Comment by lk-geimfari** [comment]
@sobolevn Great! I'll check issues out on holidays.

**Comment by Kub-AT** [comment]
As a third party library works fine with python 3.8.1

**Comment by sobolevn** [comment]
Turns out, this can be easily added. One sec.

**Comment by sobolevn** [comment]
Closed by #143 

It is now officially supported: https://github.com/sobolevn/django-split-settings/blob/master/.travis.yml
