### ISSUE TITLE
Include an absolute path file.

### ISSUE THREAD

**Issue by alexsilva** [sobolevn/django-split-settings#136]
I've been checking the code and it doesn't seem possible to include a file with absolute path. Is there any alternative in this regard ?

The code always gathers the file paths relative to the settings it calls include.

```pattern = os.path.join(conf_path, conf_file)```

**Comment by sobolevn** [comment]
Thanks for raising this question!

I would love to know more about your use-case. Why do you need the absolute path?

**Comment by alexsilva** [comment]
In my case it would be for plugins to be able to add configuration files without being in the main package.

**Comment by sobolevn** [comment]
Do you mean something like https://docs.djangoproject.com/en/3.0/ref/applications/#configuring-applications ?

**Comment by alexsilva** [comment]
Is not it. Plugins settings is loaded and added to the main project settings at startup.

**Comment by alexsilva** [comment]
Django boot

Load settings
---- Load plugins
---- Loaf plugins settings (add abs path)

**Comment by alexsilva** [comment]
A simple `os.path.isabs(conf_file)` check already solves this issue.

```
    for conf_file, __name in args:
        saved_included_file = scope.get('__included_file__')
        if not os.path.isabs(conf_file):
            pattern = os.path.join(conf_path, conf_file)
        else:
            pattern = conf_file
        # find files per pattern, raise an error if not found (unless file is
        # optional)
        files_to_include = glob.glob(pattern)
        if not files_to_include and not isinstance(conf_file, _Optional):
            raise IOError('No such file: {}'.format(pattern))
```

**Comment by sobolevn** [comment]
The thing is that I don't want to add a core support for this case. Why? 
Because generally absolute paths are a disaster! It is guaranteed not to work as someone expects.

So, I would like to find any other ways to help you in your extraordinary use-case.

**Comment by alexsilva** [comment]
ok
