### ISSUE TITLE
PyPI pages does not render rst correctly

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/django-split-settings#14]
For some reason our page on PyPI looks broken. https://pypi.python.org/pypi/django-split-settings

`rst` is not rendered.
We should fix that.

**Comment by sobolevn** [comment]
For example: https://github.com/aldryn/aldryn-django 
This repo looks good.

**Comment by lk-geimfari** [comment]
@sobolevn This is strange. Are we have `long_description` in `setup.py`?

**Comment by lk-geimfari** [comment]
This is a [setup.py](https://github.com/lk-geimfari/elizabeth/blob/master/setup.py) file of elizabeth library. It's [works](https://pypi.python.org/pypi/elizabeth/0.3.27) perfectly.
