### ISSUE TITLE
Development server autoreload on included modules changes

### ISSUE THREAD

**Issue by ygwain** [sobolevn/django-split-settings#172]
Should automatic reload work on changes in included modules under Django's development server?

**Comment by sobolevn** [comment]
Yes, it should. And it looks like it works for me. What about you?

**Comment by ygwain** [comment]
I could manage to work it, it is working for `settings/__init__.py` but not for any of included modules.
Tried on Django 2.2.12/Python 3.8.2.

**Comment by ygwain** [comment]
Seems like Django tries to be smart (at least on my setup, I suspect it might relay on how many files are watched) and does the reload only on changes of explicitly imported modules. If I do something like:
```Python
if ENV == 'development':
    from .environments import development
```
in end of `settings/__init__.py` it helps to work around the problem.

**Comment by sobolevn** [comment]
Thanks a lot for the workaround!

**Comment by ygwain** [comment]
I made small changes to the code, which adds dummy modules to `sys.modules` to automatically restart `runserver`. The current approach does not work with Django 2.2.12.

**Comment by sobolevn** [comment]
Done! https://github.com/sobolevn/django-split-settings/releases/tag/1.0.1

Thanks a lot for the fix!

**Comment by ygwain** [comment]
Thank you!
