### ISSUE TITLE
Import from  one file to another

### ISSUE THREAD

**Issue by esclkm** [sobolevn/django-split-settings#22]
I define some settings in One file
but I need to import into another 
how to do it?
for example base_dir

**Comment by sobolevn** [comment]
Hello, thanks for you question! 

Just use the normal import. Here's an example:

> ├── your_server
> │   ├── __init__.py
> │   ├── settings
> │   │   ├── __init__.py
> │   │   ├── components
> │   │   │   ├── __init__.py
> │   │   │   ├── cms.py
> │   │   │   ├── common.py
> │   │   │   └── storages.py
> │   │   └── environments
> │   │       ├── __init__.py
> │   │       ├── development.py
> │   │       ├── production.py
> │   │       └── testing.py
> │   ├── urls.py
> │   └── wsgi.py
> ├── requirements.txt
> ├── manage.py
> 

Let's imagine you need to import `BASE_DIR` from `common.py` in `production.py`.
You just write: 

```python
from your_server.settings.components.common import BASE_DIR
```

**Comment by esclkm** [comment]
One problem with default value of BASE_DIR 
```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
```
- initially - it shows application settings folder
but after glue - it shows project folder 
This is really dangerous. Thanks for fast answer

**Comment by sobolevn** [comment]
Yeap, it had to be changed. Because the directory structure also changes.
Glad to help!
