### ISSUE TITLE
Dynamic settings

### ISSUE THREAD

**Issue by leobuskin** [sobolevn/django-split-settings#24]
Nice solution, but couldn't find best practice how to use settings from one component within another one. For example, we have `components\django.py` that uses some variables from `components\common.py`, is it safety to do an import? How you organizing it? I wasn't able to find such samples in tests.

**Comment by sobolevn** [comment]
Thanks for interest!

That's how I do it.

```python
# server/settings/components/common.py

SOME_VALUE = ('setting', )
```

```python
# server/settings/components/other.py
from server.settings.components.common import SOME_VALUE

SOME_VALUE =+ ('other', )
OTHER_VALUE = 123
```

And importing all components:

```python
# server/settings/__init__.py
from split_settings.tools import optional, include

include(
    'components/common.py',
    'components/other.py',
)

# SOME_VALUE will be equal to ('setting', 'other', )
```

**Comment by leobuskin** [comment]
Perfect, thanks for the quick reply, works like a charm. We just switched to your package mostly all products and twice happier than before.
