### ISSUE TITLE
Components can't import each other.

### ISSUE THREAD

**Issue by proofit404** [sobolevn/django-split-settings#286]
Hi, thank you for the project.
***
I came to the problem:

1. Base component:
```python
DEBUG = True

INSTALLED_APPS = []
```
2. Static files component:
```python
from components.base import INSTALLED_APPS

INSTALLED_APPS.append('staticfiles')

STATICFILES_DIRS = []
```
3. Node assets component
```python
from components.base import INSTALLED_APPS
from components.staticfiles import STATICFILES_DIRS

INSTALLED_APPS.append('node_assets')

STATICFILES_DIRS.append('node_modules/')
```
4. Settings file
```python
include(
    'components/base.py',
    'components/staticfiles.py',
    'components/node_assets.py',
)
```
***
In the code example above static files component will be executed multiple times
1. Because node assets component import it.
2. By include function.

This lead to static files Django application being appended to the list twice. This will be a error according to the Django check framework.
***
To my understanding root of this problem relates to split settings implementation details. It ignores python import system and `exec` component code as strings.

Possible solutions to this problem:
- use python import system instead of exec
- give us something to else to solve this problem

Thoughts?

Regards,
Artem.

**Comment by sobolevn** [comment]
The problem with this approach is that you need to rembeber from where you need to import your `INSTALLED_APPS`.
It is really hard. That's why I use `common.py` to define this (and similar) variables.

And trust me - forbidding import cycles is a good thing! 👍
