### ISSUE TITLE
Support Django 2.1

### ISSUE THREAD

**Issue by mikelane** [sobolevn/django-split-settings#56]

**Comment by sobolevn** [comment]
I guess it will work, it is just not tested.
@mikelane do you want to contribute?

**Comment by lk-geimfari** [comment]
@sobolevn I can approve that this work perfectly with Django 2.1, cuz I use it in all my projects, including a website on `Django 2.1`.

**Comment by mikelane** [comment]
@sobolevn, I'm working on a whole new suite of tests as we speak :-)
