### ISSUE TITLE
Unresolved Libraries in Templates - PyCharm & Django 2.2

### ISSUE THREAD

**Issue by iamcb** [sobolevn/django-split-settings#71]
Following the Tutorial and creating the settings package or settings.py file and importing INSTALLED_APPS causes PyCharm to complain about unresolved libraries in HTML file.

ex: {% load staticfiles %} will give an unresolved library error

This Could be a PyCharm Issue as, as everything still runs without issue with "runserver" command.

**Comment by sobolevn** [comment]
Which file are you talking about?

**Comment by iamcb** [comment]
```
"""
project/project/settings/__init__.py
"""

import os

from split_settings.tools import include  # optional

ENV = os.environ.get('DJANGO_ENV') or 'development'

base_settings = [
	'common.py',  # standard django settings - including INSTALLED_APPS
	'database.py',  # postgres
	'logging.py',  # logging settings
	'app_settings.py',  # app specific settings

	# 'rq.py',  # redis and redis-queue
	# 'emails.py',  # SMTP

	# Select the right env:
	'environments/%s.py' % ENV,
	# Optionally override some settings:
	# optional('environments/local.py'),
]

# Include settings:
include(*base_settings)

```

Doing this creates the error in all HTML templates

**Comment by iamcb** [comment]
So i figured it out, at least sort of and things work now with PyCharm.

PyCharm does not like that INSTALLED_APPS setting gets imported, and will fail to figure out where all the tags are for the templates. In Preferences->Languages&Frameworks->Django make sure the settings file you point to has INSTALLED_APPS in it, and PyCharm is copasetic.

This does seem to break the "run manage.py" command in the tools menu, but its a small price to pay, and everything still works from the command line with "python manage.py".

This issue is with PyCharm and not with Django-split-settings so I'm closing the issue.
